/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-01-14 17:53:03 UTC)
 * on 2015-03-20 at 11:48:42 UTC 
 * Modify at your own risk.
 */

package com.appspot.massive_glyph_88905.tictactoe.model;

/**
 * ProtoRPC message definition to represent a board.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the tictactoe. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class TictactoeApiMessagesBoardMessage extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String state;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getState() {
    return state;
  }

  /**
   * @param state state or {@code null} for none
   */
  public TictactoeApiMessagesBoardMessage setState(java.lang.String state) {
    this.state = state;
    return this;
  }

  @Override
  public TictactoeApiMessagesBoardMessage set(String fieldName, Object value) {
    return (TictactoeApiMessagesBoardMessage) super.set(fieldName, value);
  }

  @Override
  public TictactoeApiMessagesBoardMessage clone() {
    return (TictactoeApiMessagesBoardMessage) super.clone();
  }

}
